version: '3.3'

services:
  db:
    image: postgres:14
    container_name: db_app
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
#    env_file:
#      - ./.env
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

    container_name: app_metamorph
    command: [ "/app/docker/app.sh" ]
    ports:
      - "9999:8000"
    depends_on:
      db:
        condition: service_healthy
