"""Initial

Revision ID: e22a24a4da2a
Revises: 
Create Date: 2024-07-19 03:16:57.834948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision: str = 'e22a24a4da2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permissions', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Create a temporary table corresponding to your model
    status_table = table('status',
                         sa.Column('id', sa.Integer),
                         sa.Column('name', sa.String),
                         sa.Column('permissions', sa.Boolean)
                         )

    # Insert rows
    op.bulk_insert(status_table,
                   [
                       {'id': 1, 'name': 'status1', 'permissions': True},
                       {'id': 2, 'name': 'status2', 'permissions': False}
                   ]
                   )

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_models',
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column('model_description', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_table('chat',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('history', sa.Text(), nullable=False),
                    sa.Column('current_token', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['current_token'], ['user_models.token'], ),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    op.drop_table('user_models')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('status')
    # ### end Alembic commands ###
